# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53e4bcb8648e0ca81db99f0ee1b2f50b4e3fb41f0e36dc1bdc014a6480bfea01017415e84d87d0ee7be69cf7de85286f9579fd4145245dfb19d5c5145394e853

test:
  secret_key_base: 3a79d3407dfd114ff10ecd245821f2b389a0d5293fb7f678252ff4b4f6969d9c6c1b37e0b0ca1a0d3212a9b66d686b93b6d13047cb6761dcd6e07faf72a2446d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
